package platform

import (
	"fmt"
	"strings"

	"github.com/gocarina/gocsv"
)

type onePasswordTeamRecord struct {
	TeamMember string `csv:"Team Member"`
	Email      string `csv:"Email"`
	Status     string `csv:"Status"`
}

// OnePasswordTeam parses the CSV file generated by the OnePassword Team page.
type OnePasswordTeam struct{}

func (p *OnePasswordTeam) Description() ProcessorDescription {
	return ProcessorDescription{
		Kind: "1password-team",
		Name: "1Password Team Members",
		Steps: []string{
			"To be documented",
			"Download resulting CSV file for analysis",

			"Execute 'acls-in-yaml --kind=1password-team --input=<path>'",
		},
	}
}

func (p *OnePasswordTeam) Process(c Config) (*Artifact, error) {
	src, err := NewSourceFromConfig(c, p)
	if err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	a := &Artifact{Metadata: src}

	records := []onePasswordTeamRecord{}
	if err := gocsv.UnmarshalBytes(src.content, &records); err != nil {
		return nil, fmt.Errorf("unmarshal: %w", err)
	}

	for _, r := range records {
		// Reduce output spam
		if r.Status == "Active" {
			r.Status = ""
		}

		u := User{
			Account: r.Email,
			Name:    strings.TrimSpace(r.TeamMember),
			Status:  r.Status,
		}

		a.Users = append(a.Users, u)
	}

	return a, nil
}
