package platform

import (
	"bytes"
	"fmt"
	"log"
	"regexp"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

// Auth0Members parses the CSV file generated by the OnePassword Team page.
type Auth0Members struct{}

func (p *Auth0Members) Description() ProcessorDescription {
	return ProcessorDescription{
		Kind: "auth0",
		Name: "Auth0 Tenant Members",
		Steps: []string{
			"Open https://manage.auth0.com/",
			"Click Settings",
			"Click Tenant Members",
			"Save this page (Complete)",
			"Collect resulting .html file for analysis (the other files are not necessary)",
			"Execute 'yacls --kind={{.Kind}} --input={{.Path}}'",
		},
		MatchingFilename: regexp.MustCompile(`Tenant Settings.html$`),
	}
}

func (p *Auth0Members) Process(c Config) (*Artifact, error) {
	src, err := NewSourceFromConfig(c, p)
	if err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}

	a := &Artifact{Metadata: src}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(src.content))
	if err != nil {
		return nil, fmt.Errorf("document: %w", err)
	}

	// Find the members
	doc.Find("tr").Each(func(i int, tr *goquery.Selection) {
		name := ""
		account := ""
		role := ""

		tr.Find("p").Each(func(i int, p *goquery.Selection) {
			attr, _ := p.Attr("class")
			log.Printf("p=%s, attr=%s", p.Text(), attr)

			if strings.Contains(p.Text(), "@") {
				account, _, _ = strings.Cut(p.Text(), "(")
				account = strings.TrimSpace(account)
				log.Printf("account=%s", account)
			} else {
				name, _, _ = strings.Cut(p.Text(), "(")
				name = strings.TrimSpace(name)
				log.Printf("name=%s", name)
			}
		})

		s := tr.Find("td").Eq(1)
		role = strings.ToLower(s.Text())

		if account != "" {
			a.Users = append(a.Users, User{Account: account, Name: name, Role: role})
		}
	})

	return a, nil
}
