package platform

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/gocarina/gocsv"
)

var githubExportRe = regexp.MustCompile(`export-([\w\-]+)-\d+.csv`)

// GithubOrgMembers parses the CSV file generated by the Github Members page.
type GithubOrgMembers struct{}

func (p *GithubOrgMembers) Description() ProcessorDescription {
	return ProcessorDescription{
		Kind: "github",
		Name: "Github Organization Members",
		Steps: []string{
			"Open https://github.com/orgs/<org>/people",
			"Click Export",
			"Select 'CSV'",
			"Download resulting CSV file for analysis",
			"Execute 'yacls --kind={{.Kind}} --input={{.Path}}'",
		},
		MatchingFilename: regexp.MustCompile(`^export-.*-\d+.csv$`),
	}
}

type githubMemberRecord struct {
	Login      string `csv:"login"`
	Name       string `csv:"name"`
	Role       string `csv:"role"`
	SAMLNameID string `csv:"saml_name_id"`
}

func (p *GithubOrgMembers) Process(c Config) (*Artifact, error) {
	org := c.Project
	if org == "" {
		base := filepath.Base(c.Path)
		matches := githubExportRe.FindStringSubmatch(base)
		if len(matches) > 1 {
			org = matches[1]
		}
	}

	if org == "" {
		return nil, fmt.Errorf("unable to detect organization from %q, please pass --project=<github organization>", c.Path)
	}

	src, err := NewSourceFromConfig(c, p)
	if err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	a := &Artifact{Metadata: src}
	if a.Metadata.ID == "" {
		a.Metadata.ID = org
	}

	records := []githubMemberRecord{}
	if err := gocsv.UnmarshalBytes(src.content, &records); err != nil {
		return nil, fmt.Errorf("unmarshal: %w", err)
	}

	for _, r := range records {
		role := r.Role

		// Keep the output smaller by hiding the default case
		if strings.ToLower(r.Role) == "member" {
			role = ""
		}

		u := User{
			Account: r.Login,
			Name:    strings.TrimSpace(r.Name),
			Role:    role,
			SSO:     r.SAMLNameID,
		}

		if strings.HasSuffix(u.Name, "Bot") || strings.HasSuffix(u.Account, "Bot") {
			a.Bots = append(a.Bots, u)
			continue
		}

		a.Users = append(a.Users, u)
	}

	return a, nil
}
