package platform

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

var webflowUserRe = regexp.MustCompile(`(.*?) \((.*?@.*?)\)`)

// WebflowMembers parses the CSV file generated by the OnePassword Team page.
type WebflowMembers struct{}

func (p *WebflowMembers) Description() ProcessorDescription {
	return ProcessorDescription{
		Kind: "webflow-members",
		Name: "Webflow Site Permissions",
		Steps: []string{
			"Open https://webflow.com/dashboard/sites/<site>/members",
			"Save this page (Complete)",
			"Collect resulting .html file for analysis (the other files are not necessary)",
			"Execute 'acls-in-yaml --webflow-members-html=<path>'",
		},
	}
}

func (p *WebflowMembers) Process(c Config) (*Artifact, error) {
	src, err := NewSourceFromConfig(c, p)
	if err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}

	a := &Artifact{Metadata: src}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(src.content))
	if err != nil {
		return nil, fmt.Errorf("document: %w", err)
	}

	// Find the members
	doc.Find("tr.member").Each(func(i int, s *goquery.Selection) {
		raw := strings.TrimSpace(s.Find("div.ng-binding").Text())
		if raw == "" {
			return
		}

		matches := webflowUserRe.FindStringSubmatch(raw)
		if len(matches) < 2 {
			return
		}

		name := matches[1]
		account := matches[2]
		role := strings.TrimSpace(s.Find("span.ng-binding").Text())

		a.Users = append(a.Users, User{Account: account, Name: name, Role: role})
	})

	return a, nil
}
